# Generated by Django 3.1.3 on 2020-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_person', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('pas_num', models.CharField(max_length=200)),
                ('pas_take', models.CharField(max_length=200)),
                ('pas_reg', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=1000)),
                ('zp', models.ImageField(upload_to='')),
                ('tours', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
