# Generated by Django 3.1.3 on 2020-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201227_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='response',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
