# Generated by Django 3.1.3 on 2020-12-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201227_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
