# Generated by Django 3.1.3 on 2020-12-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_interested_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='date',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
